window.APP_CONFIG = {
  SUPABASE_URL: "https://mmfsgzsvhktcyflarlae.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdWJhc2UiLCJyZWYiOiJtbWZzZ3pzdmhrdGN5ZmxhcmxhZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzcyMDUzNjQ0LCJleHAiOjIwODc2Mjk2NDR9.sw61EZza4jmyvy51RLUyKiBJ3p6GXjs_NsnZKAnn2TI"
};